Merge develop into Main
lsst-sitcom/sitcomtn-120 pull request #1
Opened 2024-03-25 22:04 UTC by joaquinhernandezg

First version of the M2 index technote. 

Added M2 related technotes and the documents with the M2 cell assembly specifications.

I added Bruno as author just for creating the technote as I don't have an author id in https://github.com/lsst/lsst-texmf/blob/main/etc/authordb.yaml, it was removed afterwards.

2024-03-27 21:16 UTC, Kelks19 requested changes

2024-03-27 21:16 UTC, Kelks19 commented on index.rst
1. Update the correct hyperlink to SITCOMTN-103
2. Include a one liner summary for each indexed TN e.g result of the data analysis, quantification  on how the requirements are reached like  avg with 1 sigma error etc.   
3. Are you expecting to add more TNs to this index ? If so, add a note saying that its still in development 
4. Only if applicable : You could include a 'to-do' list enlisting  the open sitcom analysis tickets that are still in progress but not yet progressed to TNs .

2024-03-28 15:16 UTC, joaquinhernandezg commented on index.rst
1. This is corrected now in a new commit, I squashed the previous commits to have a cleaner history. 
2. All those technotes are still in development, except for SITCOMTN-093, so I don't think it is worth adding much results here. 
3. For the moment, no, there are no other M2 TNs being developed at the moment. It will need to be updated if a new M2 TN is created.
4. Adding current tickets will imply the TN to be constantly updated.

The idea is just to have a place to easily access M2 related technotes and not have a detailed summary. For example, see [SITCOMTN-088](https://sitcomtn-088.lsst.io/v/SITCOM-948/index.html). I wanted to do a more detailed summary there, but Bruno said it was ok to just list the associated technotes. See the associated PR (https://github.com/lsst-sitcom/sitcomtn-088/pull/4).

2024-03-28 15:19 UTC, joaquinhernandezg commented on index.rst
I left the "This is a draft" box, which is written automatically when the TN is in development, but it should be removed when pushing to the main branch.

2024-03-28 16:19 UTC, Kelks19 approved these changes
Ok, clarified !

2024-03-28 16:28 UTC, merged